"""create hourly_rf_features table

Revision ID: 38d98864ed5c
Revises: d004683f3f0c
Create Date: 2025-09-28 21:37:22.561837

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38d98864ed5c"
down_revision: Union[str, None] = "d004683f3f0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hourly_river_flow_features",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.String(), nullable=False),
        sa.Column("flow_cfs", sa.Float(), nullable=True),
        sa.Column("prec", sa.Float(), nullable=True),
        sa.Column("tobs", sa.Float(), nullable=True),
        sa.Column("wteq", sa.Float(), nullable=True),
        sa.Column("snwd", sa.Float(), nullable=True),
        sa.Column("oni_value", sa.Float(), nullable=True),
        sa.Column("month_sin", sa.Float(), nullable=False),
        sa.Column("month_cos", sa.Float(), nullable=False),
        sa.Column("hour_sin", sa.Float(), nullable=False),
        sa.Column("hour_cos", sa.Float(), nullable=False),
        sa.Column("flow_cfs_lag1", sa.Float(), nullable=True),
        sa.Column("flow_cfs_lag3", sa.Float(), nullable=True),
        sa.Column("flow_cfs_lag6", sa.Float(), nullable=True),
        sa.Column("flow_cfs_lag24", sa.Float(), nullable=True),
        sa.Column("flow_cfs_lag168", sa.Float(), nullable=True),
        sa.Column("prec_lag1", sa.Float(), nullable=True),
        sa.Column("prec_lag3", sa.Float(), nullable=True),
        sa.Column("prec_lag6", sa.Float(), nullable=True),
        sa.Column("prec_lag24", sa.Float(), nullable=True),
        sa.Column("prec_lag168", sa.Float(), nullable=True),
        sa.Column("tobs_lag1", sa.Float(), nullable=True),
        sa.Column("tobs_lag3", sa.Float(), nullable=True),
        sa.Column("tobs_lag6", sa.Float(), nullable=True),
        sa.Column("tobs_lag24", sa.Float(), nullable=True),
        sa.Column("tobs_lag168", sa.Float(), nullable=True),
        sa.Column("wteq_lag1", sa.Float(), nullable=True),
        sa.Column("wteq_lag3", sa.Float(), nullable=True),
        sa.Column("wteq_lag6", sa.Float(), nullable=True),
        sa.Column("wteq_lag24", sa.Float(), nullable=True),
        sa.Column("wteq_lag168", sa.Float(), nullable=True),
        sa.Column("snwd_lag1", sa.Float(), nullable=True),
        sa.Column("snwd_lag3", sa.Float(), nullable=True),
        sa.Column("snwd_lag6", sa.Float(), nullable=True),
        sa.Column("snwd_lag24", sa.Float(), nullable=True),
        sa.Column("snwd_lag168", sa.Float(), nullable=True),
        sa.Column("flow_cfs_rollmean_3h", sa.Float(), nullable=True),
        sa.Column("flow_cfs_rollstd_3h", sa.Float(), nullable=True),
        sa.Column("flow_cfs_rollsum_3h", sa.Float(), nullable=True),
        sa.Column("flow_cfs_rollmean_6h", sa.Float(), nullable=True),
        sa.Column("flow_cfs_rollstd_6h", sa.Float(), nullable=True),
        sa.Column("flow_cfs_rollsum_6h", sa.Float(), nullable=True),
        sa.Column("flow_cfs_rollmean_24h", sa.Float(), nullable=True),
        sa.Column("flow_cfs_rollstd_24h", sa.Float(), nullable=True),
        sa.Column("flow_cfs_rollsum_24h", sa.Float(), nullable=True),
        sa.Column("flow_cfs_rollmean_168h", sa.Float(), nullable=True),
        sa.Column("flow_cfs_rollstd_168h", sa.Float(), nullable=True),
        sa.Column("flow_cfs_rollsum_168h", sa.Float(), nullable=True),
        sa.Column("prec_rollmean_3h", sa.Float(), nullable=True),
        sa.Column("prec_rollstd_3h", sa.Float(), nullable=True),
        sa.Column("prec_rollsum_3h", sa.Float(), nullable=True),
        sa.Column("prec_rollmean_6h", sa.Float(), nullable=True),
        sa.Column("prec_rollstd_6h", sa.Float(), nullable=True),
        sa.Column("prec_rollsum_6h", sa.Float(), nullable=True),
        sa.Column("prec_rollmean_24h", sa.Float(), nullable=True),
        sa.Column("prec_rollstd_24h", sa.Float(), nullable=True),
        sa.Column("prec_rollsum_24h", sa.Float(), nullable=True),
        sa.Column("prec_rollmean_168h", sa.Float(), nullable=True),
        sa.Column("prec_rollstd_168h", sa.Float(), nullable=True),
        sa.Column("prec_rollsum_168h", sa.Float(), nullable=True),
        sa.Column("tobs_rollmean_3h", sa.Float(), nullable=True),
        sa.Column("tobs_rollstd_3h", sa.Float(), nullable=True),
        sa.Column("tobs_rollmean_6h", sa.Float(), nullable=True),
        sa.Column("tobs_rollstd_6h", sa.Float(), nullable=True),
        sa.Column("tobs_rollmean_24h", sa.Float(), nullable=True),
        sa.Column("tobs_rollstd_24h", sa.Float(), nullable=True),
        sa.Column("tobs_rollmean_168h", sa.Float(), nullable=True),
        sa.Column("tobs_rollstd_168h", sa.Float(), nullable=True),
        sa.Column("wteq_rollmean_3h", sa.Float(), nullable=True),
        sa.Column("wteq_rollstd_3h", sa.Float(), nullable=True),
        sa.Column("wteq_rollmean_6h", sa.Float(), nullable=True),
        sa.Column("wteq_rollstd_6h", sa.Float(), nullable=True),
        sa.Column("wteq_rollmean_24h", sa.Float(), nullable=True),
        sa.Column("wteq_rollstd_24h", sa.Float(), nullable=True),
        sa.Column("wteq_rollmean_168h", sa.Float(), nullable=True),
        sa.Column("wteq_rollstd_168h", sa.Float(), nullable=True),
        sa.Column("snwd_rollmean_3h", sa.Float(), nullable=True),
        sa.Column("snwd_rollstd_3h", sa.Float(), nullable=True),
        sa.Column("snwd_rollmean_6h", sa.Float(), nullable=True),
        sa.Column("snwd_rollstd_6h", sa.Float(), nullable=True),
        sa.Column("snwd_rollmean_24h", sa.Float(), nullable=True),
        sa.Column("snwd_rollstd_24h", sa.Float(), nullable=True),
        sa.Column("snwd_rollmean_168h", sa.Float(), nullable=True),
        sa.Column("snwd_rollstd_168h", sa.Float(), nullable=True),
        sa.Column("snowmelt_proxy", sa.Float(), nullable=True),
        sa.Column("prec_tobs", sa.Float(), nullable=True),
        sa.Column("tobs_snwd", sa.Float(), nullable=True),
        sa.Column("prec_efficiency", sa.Float(), nullable=True),
        sa.Column("oni_lag1m", sa.Float(), nullable=True),
        sa.Column("oni_interaction", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("timestamp", "site_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hourly_river_flow_features")
    # ### end Alembic commands ###
