"""Update pkey to composite site_id<>timestamp comp key

Revision ID: 64cafce597c8
Revises: 7e8c56ef3c00
Create Date: 2024-05-11 08:46:12.442987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64cafce597c8'
down_revision: Union[str, None] = '7e8c56ef3c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('site_conditions_pkey', 'site_conditions', type_='primary')
    op.drop_column('site_conditions', 'id')
    op.create_primary_key(
        "site_conditions_pkey", "site_conditions", ["site_id", "timestamp"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_conditions', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('site_conditions_pkey', 'site_conditions', type_='primary')
    op.create_primary_key(
        "site_conditions_pkey", "site_conditions", ["id"]  # Assuming 'id' was the old primary key
    )

    # ### end Alembic commands ###
