"""Add Snotel table

Revision ID: a6af53732edf
Revises: 196bf4af13d4
Create Date: 2025-04-11 18:07:31.385262

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6af53732edf"
down_revision: Union[str, None] = "196bf4af13d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "snotel",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("station_triplets", sa.String(), nullable=False),
        sa.Column("prec", sa.Float(), nullable=True),
        sa.Column("tobs", sa.Float(), nullable=True),
        sa.Column("wteq", sa.Float(), nullable=True),
        sa.Column("snwd", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("timestamp", "station_triplets"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("snotel")
    # ### end Alembic commands ###
