"""Added ONI table

Revision ID: d004683f3f0c
Revises: a6af53732edf
Create Date: 2025-08-31 14:23:48.705018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd004683f3f0c'
down_revision: Union[str, None] = 'a6af53732edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oni',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('djf', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('jfm', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('fma', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('mam', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('amj', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('mjj', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('jja', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('jas', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('aso', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('son', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('ond', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('ndj', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oni')
    # ### end Alembic commands ###
